### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/v1/account

###
GET http://localhost:8080/api/v1/account/1

###
POST http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "name": "",
  "email": ""
}

###
PUT http://localhost:8080/api/v1/account/1
Content-Type: application/json

{
  "name": "",
  "email": ""
}

###
DELETE http://localhost:8080/api/v1/account/1