### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/v1/budget

###
GET http://localhost:8080/api/v1/budget/1

###
GET http://localhost:8080/api/v1/budget/1/MARCH

###
GET http://localhost:8080/api/v1/budget/monthly-budget/1/MARCH

###
GET http://localhost:8080/api/v1/budget/overspent-budgets/1/MARCH

###
POST http://localhost:8080/api/v1/budget
Content-Type: application/json

{
  "account": {
    "id": 1
  },
  "budgetCategory": "LEISURE",
  "budgetTotal": "200",
  "budgetMonth": "MARCH"
}

###
PUT http://localhost:8080/api/v1/budget/1
Content-Type: application/json

{
  "budgetTotal": 100
}

###
DELETE http://localhost:8080/api/v1/budget/1




