### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/v1/income

###
GET http://localhost:8080/api/v1/income/1

###
POST http://localhost:8080/api/v1/income
Content-Type: application/json

{
  "account": {
    "id": "1"
  },
  "amount": 600,
  "source": "Passive income",
  "dateReceived": "2026-03-28",
  "frequency": "MONTHLY",
  "description": "Forex trading"
}

###
PUT http://localhost:8080/api/v1/income/1
Content-Type: application/json

{
  "frequency": "WEEKLY"
}

###
DELETE http://localhost:8080/api/v1/income/1